name: test-action
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "30 8 * * *"

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:

      - name: Pull Docker image
        run: docker image pull techallylw/vulnerable-container:v0.0.1

      - name: lacework/lw-scanner-action@v1.3.0
        with:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          IMAGE_NAME: techallylw/vulnerable-container
          IMAGE_TAG: v0.0.1
